steps:
  - name: maven:3-openjdk-11
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-openjdk-11
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/store", "--build-arg=JAR_FILE=target/store-0.0.1-SNAPSHOT.jar", "."]
images: ["gcr.io/$PROJECT_ID/store"]
